name: Telegram Auto Poster

on:
  schedule:
    - cron: "*/10 * * * *" # каждые 10 минут проверяем (можно менять)
  workflow_dispatch: # запуск вручную через GitHub Actions

jobs:
  post:
    runs-on: ubuntu-latest
    permissions:
      contents: write # нужно, чтобы пушить sent.json обратно

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      OWNER_ID: ${{ secrets.OWNER_ID }}
      LINK_ORDER: ${{ secrets.LINK_ORDER }}
      MAX_PER_RUN: 1 # максимум 1 пост за прогон
      TZ: Europe/Kaliningrad # твой часовой пояс

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install lightweight deps
        run: npm install csv-parse@5 node-fetch@3

      - name: Debug time / env
        run: |
          echo "Current UTC time: $(date -u)"
          echo "Current local time: $(TZ=$TZ date)"

      - name: Run cron poster (verbose)
        run: |
          set -e
          node scripts/cron_poster.js

      - name: Commit & push sent.json (robust)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git pull --rebase || true
          git add sent.json
          git commit -m "chore: update sent.json (auto poster)" || echo "Nothing to commit"
          git push || echo "Nothing to push"
