name: Telegram Auto Poster

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install csv-parser
        run: npm i csv-parser

      - name: Run cron poster
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          WINDOW_MINUTES: "12"
        run: node scripts/cron_poster.js

      - name: Commit sent.json
        run: |
          if git diff --quiet --exit-code -- sent.json; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add sent.json
            git commit -m "chore: update sent.json (auto poster)"
            git push
          fi

          fi
